version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: release-it
    versions:
    - 14.2.2
    - 14.3.0
    - 14.4.0
    - 14.4.1
    - 14.5.0
    - 14.5.1
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: ember-cli-typescript
    versions:
    - 4.0.0
  - dependency-name: jquery
    versions:
    - 3.5.1
